# Generated by Django 4.1.4 on 2023-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geography/static/geography/img')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Proportion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('value', models.IntegerField(verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Доля вакансий в городе',
                'verbose_name_plural': 'Доля вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('value', models.IntegerField(verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Средняя зарплата в городе',
                'verbose_name_plural': 'Средние зарплаты по городам',
            },
        ),
    ]
