# Generated by Django 4.1.4 on 2023-01-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('is_header', models.BooleanField(null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/static/skills/img')),
                ('has_picture', models.BooleanField(null=True, verbose_name='Есть картинка')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
            },
        ),
    ]
