# Generated by Django 4.1.4 on 2023-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_alter_demand_options_alter_demand_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterField(
            model_name='demand',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='count_by_prof',
            field=models.IntegerField(verbose_name='Количество (Python-программист)'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='salary',
            field=models.IntegerField(verbose_name='Уровень зарплат'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='salary_by_prof',
            field=models.IntegerField(verbose_name='Уровень зарплат(Python-программист)'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
