# Generated by Django 4.1.4 on 2023-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_picture_alter_demand_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='demand/static/demand/img'),
        ),
    ]
