# Generated by Django 4.1.4 on 2023-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill1', models.CharField(max_length=20, verbose_name='Навык 1')),
                ('skill1_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill2', models.CharField(max_length=20, verbose_name='Навык 2')),
                ('skill2_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill3', models.CharField(max_length=20, verbose_name='Навык 3')),
                ('skill3_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill4', models.CharField(max_length=20, verbose_name='Навык 4')),
                ('skill4_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill5', models.CharField(max_length=20, verbose_name='Навык 5')),
                ('skill5_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill6', models.CharField(max_length=20, verbose_name='Навык 6')),
                ('skill6_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill7', models.CharField(max_length=20, verbose_name='Навык 7')),
                ('skill7_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill8', models.CharField(max_length=20, verbose_name='Навык 8')),
                ('skill8_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill9', models.CharField(max_length=20, verbose_name='Навык 9')),
                ('skill9_count', models.IntegerField(verbose_name='Количество повторений')),
                ('skill10', models.CharField(max_length=20, verbose_name='Навык 10')),
                ('skill10_count', models.IntegerField(verbose_name='Количество повторений')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
