# Generated by Django 4.1.4 on 2023-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/static/skills/img'),
        ),
    ]
