# Generated by Django 4.1.4 on 2023-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_text_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='is_header',
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'h1'), (2, 'h2'), (3, 'p')], null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index/static/index/img'),
        ),
    ]
