# Generated by Django 4.1.4 on 2023-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_text_is_header_text_type_alter_text_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/static/skills/img'),
        ),
    ]
