# Generated by Django 4.1.4 on 2023-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_text_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_header',
            field=models.BooleanField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index/static/index/img'),
        ),
    ]
