# Generated by Django 4.1.4 on 2023-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_text_is_header_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_list',
            field=models.BooleanField(null=True, verbose_name='Перечисление'),
        ),
    ]
