# Generated by Django 4.1.4 on 2023-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_text_elems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
