# Generated by Django 4.1.4 on 2023-01-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='elems',
        ),
        migrations.RemoveField(
            model_name='text',
            name='is_list',
        ),
    ]
