# Generated by Django 4.1.4 on 2023-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_delete_picture_text_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='has_picture',
            field=models.BooleanField(null=True, verbose_name='Есть картинка'),
        ),
    ]
